server:
  port: 9023

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CREATE-SERVICE
          uri: lb://CREATE-SERVICE
          predicates:
            - Path=/create/**
        - id: GET-SERVICE
          uri: lb://GET-SERVICE
          predicates:
            - Path=/get/**
        - id: GETALL-SERVICE
          uri: lb://GETALL-SERVICE
          predicates:
            - Path=/getAll/**

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka